GRADES = {
    "_OK_": {"rating": 5, "grade": "Perfect pass", "legend": "PERFECT"},
    "OK": {"rating": 4, "grade": "Minimum deviation with good correction", "color": "#29C248", "legend": "OK"},
    "(OK)": {"rating": 3, "grade": "Reasonable deviation with avg. correction", "color": "#F2C038", "legend": "FAIR"},
    "B": {"rating": 2.5, "grade": "No wire-catch, go-around needed", "color": '#088199', "legend": "BOLTER"},
    "--": {"rating": 2, "grade": "No grade. Below average corrections but safe pass", "color": "#73481d", "legend": "NO GRADE"},
    "WO": {"rating": 1, "grade": "Wave-off", "color": "#000000", "legend": "WAVE OFF"},
    "C": {"rating": 0, "grade": "Cut. Unsafe, gross deviations inside the wave-off window", "color": "#CC0000", "legend": "CUT"},
    "NC": {"rating": 0, "grade": "No count", "color": "#FFFFFF", "legend": "NO COUNT"},
    "_n": {"color": "#000000", "legend": "Night pass"}
}

ERRORS = {
    "WO(AFU)": "Waved off (all fouled up)",
    "3PTS": "Landed 3 points",
    "LLWD": "Landed left wing down",
    "LRWD": "Landed right wing down",
    "NERD": "Not enough rate of descent",
    "NERR": "Not enough right rudder",
    "NESA": "Not enough straight away",
    "OSCB": "Overshot coming back",
    "TMRD": "Too much rate of descent",
    "TMRR": "Too much right rudder",
    "XCTL": "Cross control",
    "ACC": "Accelerate",
    "AFU": "All fouled up",
    "DEC": "DEC Decelerate",
    "DLW": "Left wing down",
    "DRW": "Right wing down",
    "LIG": "Long in the groove",
    "LLU": "Late lineup",
    "LNF": "Landed nose first",
    "LTR": "Left to right",
    "LUL": "Lined up left",
    "LUR": "Lined up right",
    "LWD": "Left wing down",
    "NEA": "Not enough attitude",
    "NEP": "Not enough power",
    "NSU": "Not set up",
    "PNU": "Pulled nose up",
    "PPP": "Power, power, power",
    "ROT": "Rotate",
    "RTL": "Right to left",
    "RUD": "Rudder",
    "RUF": "Rough",
    "RWD": "Right wing down",
    "SHT": "Ship’s turn",
    "SKD": "Skid",
    "SLO": "Slow",
    "SRD": "Stopped rate of descent",
    "TCA": "Too close abeam",
    "TMA": "Too much attitude",
    "TMP": "Too much power",
    "TTL": "Turned too late",
    "TTS": "Turned too soon",
    "TWA": "Too wide abeam",
    "AA": "Angling approach",
    "BC": "",
    "CB": "Coming Back to Lineup",
    "CD": "Coming Down",
    "CH": "Chased",
    "CO": "Come-on",
    "CU": "Cocked up",
    "DD": "Deck down",
    "DN": "DN Dropped nose",
    "DL": "Drifted left",
    "DR": "Drifted right",
    "DU": "DU Deck up",
    "EG": "Eased gun (cut throttle on touchdown)",
    "FD": "Fouled deck",
    "HO": "Hold off",
    "LL": "Landed left",
    "LO": "Low",
    "LR": "Landed right",
    "LU": "Lineup",
    "NC": "Nice correction",
    "ND": "Nose down",
    "NH": "No hook",
    "OC": "Over corrected",
    "OR": "Overrotate",
    "OS": "Overshoot",
    "PD": "Pitching deck",
    "RR": "Right rudder",
    "SD": "Spotted deck",
    "ST": "Steep turn",
    "WO": "Wave-off",
    "WU": "Wrapped up",
    "B": "Flat Glideslope",
    "C": "Climbing",
    "F": "Fast",
    "H": "High",
    "N": "Nose",
    "P": "Power",
    "S": "Settle",
    "W": "Wings"
}

DISTANCE_MARKS = {
    "XX": "At the start (first 1/3 of the glideslope)",
    "X0": "Entering the groove",
    "X": "At the start (first 1/3 of the glideslope)",
    "IM": "In the middle (second 1/3 of the glideslope)",
    "BC": "Ball call",
    "IC": "In close (last 1/3 of the glideslope)",
    "AR": "At the ramp",
    "AL": "Abeam landing position (V/STOL)",
    "TL": "To land",
    "LC": "Level crossing (V/STOL)",
    "IW": "In the wires",
    "AW": "All the way"
}
