# const.py
METER_IN_FEET = 3.28084
METER_PER_SECOND_IN_KNOTS = 1.94384
MMHG_IN_INHG = 0.0393701

SIDE_UNKNOWN = -1
SIDE_SPECTATOR = 0
SIDE_RED = 1
SIDE_BLUE = 2
SIDE_NEUTRAL = 3

PLAYER_SIDES = {
    SIDE_UNKNOWN: 'UNKNOWN',
    SIDE_SPECTATOR: 'SPECTATOR',
    SIDE_RED: 'RED',
    SIDE_BLUE: 'BLUE',
    SIDE_NEUTRAL: 'NEUTRAL'
}
