ALTER TABLE players ADD COLUMN IF NOT EXISTS synced BOOLEAN DEFAULT FALSE;
ALTER TABLE bans ADD COLUMN IF NOT EXISTS synced BOOLEAN NOT NULL DEFAULT FALSE;
CREATE TABLE whitelist (player_ucid TEXT NOT NULL PRIMARY KEY, FOREIGN KEY (player_ucid) REFERENCES players (ucid) ON UPDATE CASCADE ON DELETE CASCADE);
