repository: Special-K-s-Flightsim-Bots/DCSServerBot
title: DCSServerBot
description: A Python tool to manage DCS-servers via Discord
theme: just-the-docs
color_scheme: dcsserverbot

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: https://github.com/Special-K-s-Flightsim-Bots/DCSServerBot
gh_edit_branch: main
gh_edit_source: docs
gh_edit_view_mode: edit

callouts_level: quiet # or loud
callouts:
  highlight:
    color: grey-dk
  important:
    title: Important
    color: red
  new:
    title: New
    color: grey-lt
  note:
    title: Note
    color: green
  warning:
    title: Warning
    color: yellow
callouts_opacity: 0.4

aux_links:
  GitHub: https://github.com/Special-K-s-Flightsim-Bots/DCSServerBot
  Discord: https://discord.gg/h2zGDH9szZ
  Patreon: https://www.patreon.com/DCS_SpecialK
