ALTER TABLE servers DROP COLUMN host;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS status_channel BIGINT NOT NULL DEFAULT -1;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS chat_channel BIGINT NOT NULL DEFAULT -1;
ALTER TABLE servers RENAME COLUMN agent_host TO node;
CREATE TABLE IF NOT EXISTS intercom (id SERIAL PRIMARY KEY, node TEXT NOT NULL, time TIMESTAMP NOT NULL DEFAULT NOW(), data JSON);
CREATE TABLE IF NOT EXISTS node (guild_id BIGINT NOT NULL, node TEXT NOT NULL, master BOOLEAN NOT NULL, last_seen TIMESTAMP DEFAULT NOW(), PRIMARY KEY (guild_id, node));
CREATE TABLE IF NOT EXISTS config_nodes (guild_id BIGINT NOT NULL, node TEXT NOT NULL, param TEXT NOT NULL, value TEXT NOT NULL);
UPDATE version SET version='v1.7';
